---

- name: see if shairport is already installed
  command: which shairport-sync
  changed_when: false
  failed_when: false
  register: which_shairport

- name: ensure that there is no present version
  ansible.builtin.file:
    path: "{{ which_shairport.stdout }}"
    state: absent
  when: which_shairport.rc == 0

- name: remove old configfiles
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/systemd/system/shairport-sync.service"
    - "/lib/systemd/system/shairport-sync.service"
    - "/etc/init.d/shairport-sync"
    - "/etc/dbus-1/system.d/shairport-sync-dbus.conf"
    - "/etc/dbus-1/system.d/shairport-sync-mpris.conf"

- name: install build dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ shairport_build_deps }}"
