---
# defaults file for shairport-install
shairport_build_deps:
  - autoconf
  - automake
  - avahi-daemon
  - build-essential
  - git
  - libasound2-dev
  - libavahi-client-dev
  - libconfig-dev
  - libpopt-dev
  - libsoxr-dev
  - libssl-dev
  - libtool
  - xmltoman

shairport_git_url: https://github.com/mikebrady/shairport-sync.git
shairport_build_dir: /opt/shairport-source
