---
# tasks file for shairport-configure

- name: copy the shairport config file
  ansible.builtin.copy:
    src: "shairport-sync.conf"
    dest: "{{ shairport_conf_path }}"
  notify: restart_shairport
