---

- name: see if shairport is already installed
  command: which shairport-sync
  changed_when: false
  failed_when: false
  register: which_shairport

- name: ensure that there is no present version
  ansible.builtin.file:
    path: "{{ which_shairport.stdout }}"
    state: absent
  when: which_shairport.rc == 0

- name: remove old configfiles
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/systemd/system/shairport-sync.service"
    - "/lib/systemd/system/shairport-sync.service"
    - "/etc/init.d/shairport-sync"
    - "/etc/dbus-1/system.d/shairport-sync-dbus.conf"
    - "/etc/dbus-1/system.d/shairport-sync-mpris.conf"

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: install build dependencies
  ansible.builtin.apt:
    name: "{{ shairport_build_deps }}"
    state: present

- name: clone the repository
  ansible.builtin.git:
    repo: "{{ shairport_git_url }}"
    dest: "{{ shairport_build_dir }}"
    update: true
    accept_hostkey: true

- name: build the project
  ansible.builtin.command:
    cmd: "{{ item }}"
    chdir: "{{ shairport_build_dir }}"
  with_items:
    - "autoreconf -fi"
    - "./configure --sysconfdir=/etc --with-alsa --with-soxr --with-avahi --with-ssl=openssl --with-systemd"
    - "make"
    - "make install"

- name: create the shairport dir
  ansible.builtin.file:
    path: "/home/shairport-sync/.config/pulse"
    state: directory
    mode: '0755'
    owner: shairport-sync

- name: reload the systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    name: shairport-sync
    enabled: yes
    state: started
